services:
  # Redis
  redis:
    image: eqalpha/keydb
    ports:
      - "6379:6379"

  # MongoDB
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.data/db:/data/db

  # MinIO
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioautumn
      MINIO_ROOT_PASSWORD: minioautumn
    volumes:
      - ./.data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always

  # Create buckets for minio.
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minioautumn
      MINIO_ROOT_PASSWORD: minioautumn
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      while ! /usr/bin/mc ready minio; do echo 'Waiting for minio...' && sleep 5; done;
      sleep 10;
      /usr/bin/mc mb minio/revolt-uploads || echo 'Bucket already exists';
      exit 0;
      "
