# ⚠️ This configuration is intended for development environment.
# If you'd like to override anything, create a Revolt.override.toml

[database]
# MongoDB connection URL
# Defaults to the container name specified in self-hosted
mongodb = "mongodb://127.0.0.1:27017"
# Redis connection URL
# Defaults to the container name specified in self-hosted
redis = "redis://127.0.0.1:6379/"

[hosts]
# Web locations of various services
# Defaults assume all services are reverse-proxied
# See https://github.com/revoltchat/self-hosted/blob/master/Caddyfile
#
# Remember to change these to https/wss where appropriate in production!
app = "http://0.0.0.0:14701"
api = "http://0.0.0.0:14702"
events = "ws://0.0.0.0:14703"
autumn = "http://0.0.0.0:9000"
january = "http://0.0.0.0:14705"

voso_legacy = ""
voso_legacy_ws = ""

[api]

[api.smtp]
host = "smtp.mail.ru"
username = "ruskord.olegovich@mail.ru"
password = "gc1e4KCkMwqC8zBA6E5W"
from_address = "ruskord.olegovich@mail.ru"
reply_to = "ruskord.olegovich@mail.ru"
port = 587
use_tls = true

[files.s3]
endpoint = "http://127.0.0.1:9000"
region = "minio"
access_key_id = "minioautumn"
secret_access_key = "minioautumn"
default_bucket = "revolt-uploads"

